### ISSUE TITLE
Document the cursors

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/overtone#36]
The game executable has 17 cursors:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/92793/210102944-2b5f87f0-d12d-427e-b500-f604a0141dcf.png">

We should figure out what cursors are used when, for further usage in game.

The resulting "documentation" may be put into a form of source code in `Mouse.fs` and `CursorShape` enum inside of the `Input.fs` file.

**Comment by Fadoli** [comment]
Hey, I'm willing to startup the original game and document when those cursors happens

**Comment by Fadoli** [comment]
3 : When casting a spell on building, and hovering a building (pair with cursor 14)
4 : When hovering a selectable entity (unit, building, building spot, bridge, ...) is under the cursor
5 : When in "help" mode, this is used to have informations about stuff in the game
6 : Attack unit order (from the dojo's order)
7 : Attack unit order (from the dojo's order), with a valid target (only unit)
8 : Defend unit order (from the dojo's order)
9 : Defend unit order (from the dojo's order), with a valid target (only unit)
10 : ???
11 : When casting a spell on a unit (i believe)
12 : When moving a building
13 : When moving a building, on a building slot (even if a building is already there)
14 : When casting a spell on building, and not hovering a building (pair with cursor 3)
15 : Attack building order (from the dojo's order)
16 : Attack building order (from the dojo's order), with a valid target (only building)
17 : Defend building order (from the dojo's order)
18 : Does not seems to work on my PC (should be with a valid target)
19 : Default cursor

**Comment by ForNeVeR** [comment]
> 10 : ???

I was watching [a game speedrun on YouTube](https://youtu.be/Bng2cyBC0Gg?si=FlIE2pIg3ELyiAO2&t=1473) when noticed this cursor on 24:33.

The speedrunner chosen a particular spell and the cursor has appeared.

<img width="719" alt="image" src="https://github.com/ForNeVeR/overtone/assets/92793/867949e9-dec2-4bd5-bfcb-39bd889fa74c">
