### ISSUE TITLE
OSx graphic

### ISSUE THREAD

**Issue by Lewiscowles1986** [ForNeVeR/overtone#58]
![float](https://github.com/ForNeVeR/overtone/assets/2605791/33dd7fd6-74ef-4e06-9c5a-0d44fc8b9731)
I used this icon and upscaled to 512x512 using GIMP

Then I ran the following

```
mkdir -p ~/Downloads/Float.iconset
cp ~/Downloads/Float.png ~/Downloads/Float.iconset/icon_512.png
sips -Z 256 ~Downloads/icon_512.png --out ~/Downloads/Float.iconset/icon_256.png
sips -Z 128 ~Downloads/icon_512.png --out ~/Downloads/Float.iconset/icon_128.png
sips -Z 96 ~Downloads/icon_512.png --out ~/Downloads/Float.iconset/icon_96.png
sips -Z 64 ~Downloads/icon_512.png --out ~/Downloads/Float.iconset/icon_64.png
sips -Z 48 ~Downloads/icon_512.png --out ~/Downloads/Float.iconset/icon_48.png
sips -Z 32 ~Downloads/icon_512.png --out ~/Downloads/Float.iconset/icon_32.png
sips -Z 16 ~Downloads/icon_512.png --out ~/Downloads/Float.iconset/icon_16.png
cd ~/Downloads
iconutil -c icns Float.iconset -o Float.icns
```

[Float.icns.zip](https://github.com/ForNeVeR/overtone/files/13466817/Float.icns.zip)

**Comment by ForNeVeR** [comment]
Thanks for contribution!

I have to say that there are no plans to directly reuse this so far, unfortunately.

One of the purposes of Overtone is to not directly reuse any copyrighted assets, even though the game is abandonware. We would not be able to reuse this icon made from the original game's sprite and bundle it with ourselves.

The current plan is to always download all the content from the internet (hopefully it'll always be available _somewhere_), to keep the game code and produced binaries 100% clean from the copyright claims.

In particular about the game icon, I thought to just draw a new one ourselves, without reusing the original content.

(In the long-term future, I am also thinking of releasing a free content pack for the game, similar to how [FreeDOOM](https://freedoom.github.io/) works for the open-source DOOM ports, allowing to create a fully free DOOM distribution without any reliance on the copyrighted assets.)
